AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  UKPassportFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./UK.Passport.Lambda/
      Handler: UK.Passport.Lambda::UK.Passport.Lambda.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        UKPassport:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ukpassport
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UKPassportApi:
    Description: "API Gateway endpoint URL for Prod stage for UK Passport function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/UKPassport/"
  UKPassportFunction:
    Description: "UK Passport Lambda Function ARN"
    Value: !GetAtt UKPassportFunction.Arn
  UKPassportFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UKPassportFunctionRole.Arn
